// Mock data for swipe cards
export const SWIPE_CARDS_DATA = [
    // Users
    {
        id: "user-1",
        type: "user",
        name: "Thiago Alca",
        age: 25,
        image: require("../../attached_assets/stock_images/person_dancing_happi_798bff4b.jpg"),
        location: "Estrada da Barra, 1738 - Rio de Janeiro",
        bio: "Professor de Sertanejo Mod tenho pela arte da dança!",
        tags: ["SERTANEJO"],
        experience: "EXPERIÊNCIA",
    },
    {
        id: "user-2",
        type: "user",
        name: "Luiza Leoncio",
        age: 25,
        image: require("../../attached_assets/stock_images/person_dancing_happi_214e72d0.jpg"),
        location: "Estrada da Barra, 1738 - Rio de Janeiro",
        bio: "Estudante de Medicina e apaixonada pela dança.",
        tags: ["FORRÓ", "ZOUK"],
        experience: "EXPERIÊNCIA",
    },
    {
        id: "user-3",
        type: "user",
        name: "Carlos Silva",
        age: 28,
        image: require("../../attached_assets/stock_images/person_dancing_happi_8c1c5cba.jpg"),
        location: "Copacabana - Rio de Janeiro",
        bio: "Dançarino profissional de salsa e bachata.",
        tags: ["SALSA", "BACHATA"],
        experience: "PROFISSIONAL",
    },

    // Teachers
    {
        id: "teacher-1",
        type: "teacher",
        name: "Prof. Ana Costa",
        age: 32,
        image: require("../../attached_assets/stock_images/person_dancing_happi_0e460040.jpg"),
        location: "Barra da Tijuca - Rio de Janeiro",
        bio: "Professora certificada de Zouk com 10 anos de experiência.",
        tags: ["ZOUK", "TANGO"],
        experience: "PROFESSORA",
    },
    {
        id: "teacher-2",
        type: "teacher",
        name: "Prof. Ricardo Mendes",
        age: 35,
        image: require("../../attached_assets/stock_images/person_dancing_happi_24afcbbe.jpg"),
        location: "Lapa - Rio de Janeiro",
        bio: "Especialista em Samba de Gafieira e Forró Universitário.",
        tags: ["SAMBA", "FORRÓ"],
        experience: "PROFESSOR",
    },

    // Events
    {
        id: "event-1",
        type: "event",
        name: "Bosque Bar",
        image: require("../../attached_assets/stock_images/ballroom_dancing_cou_a3f721af.jpg"),
        location: "Epitácio Pessoa 420, Lagoa - Rio de Janeiro",
        bio: "Balada de música variada na Zona Sul.",
        tags: ["SALSA", "ZOUK", "FORRÓ"],
        category: "ESCOLAS DE DANÇA",
    },
    {
        id: "event-2",
        type: "event",
        name: "Samba na Lapa",
        image: require("../../attached_assets/stock_images/ballroom_dancing_cou_83e25a1a.jpg"),
        location: "Centro - Rio de Janeiro",
        bio: "Tradicional roda de samba toda sexta-feira.",
        tags: ["SAMBA"],
        category: "EVENTOS",
    },

    // Schools
    {
        id: "school-1",
        type: "school",
        name: "Academia Dança Rio",
        image: require("../../attached_assets/stock_images/ballroom_dancing_cou_4ebc2182.jpg"),
        location: "Botafogo - Rio de Janeiro",
        bio: "Escola especializada em danças de salão e latinas.",
        tags: ["SALSA", "TANGO", "ZOUK"],
        category: "ESCOLAS DE DANÇA",
    },
    {
        id: "school-2",
        type: "school",
        name: "Studio Forró Carioca",
        image: require("../../attached_assets/stock_images/ballroom_dancing_cou_7a8e006d.jpg"),
        location: "Tijuca - Rio de Janeiro",
        bio: "A melhor escola de forró do Rio de Janeiro.",
        tags: ["FORRÓ", "XOTE"],
        category: "ESCOLAS DE DANÇA",
    },
];
